### ISSUE TITLE
做一个Deepin版本的

### ISSUE THREAD

**Issue by sonichy** [BLumia/pineapple-calendar#3]
KDE版的都做好了，为啥不做个Deepin的？
README请配一张预览图。
把这个代码看懂，是不是可以开发KDE任务栏插件了？

**Comment by BLumia** [comment]
> KDE版的都做好了，为啥不做个Deepin的？

抱歉我并不用 Deepin 桌面环境（我个人一直都是使用 KDE 的），我也不靠此插件盈利，所以没有计划刻意支持其它环境。

> README请配一张预览图。

https://store.kde.org/p/1465439/ 这里其实有，https://github.com/BLumia/pineapple-calendar/issues/1 也有评论包含截图。我粘贴一张好了。

![暗色主题中的此组件截图](https://user-images.githubusercontent.com/10095765/114592414-7e7ff880-9cbd-11eb-9d56-63ed6c787a3b.png)

> 把这个代码看懂，是不是可以开发KDE任务栏插件了？

其实开发 KDE 任务栏插件不用完全看懂此项目的代码，当然反正此项目也不复杂。你能看懂肯定就能写。

如果你只是对 KDE 的桌面小部件或者任务栏小部件开发感兴趣的话，可以在了解 QML 基础知识后，参阅 KDE 的官方文档，或者 [zren 的教程](https://zren.github.io/kde/docs/widget/)。

**Comment by sonichy** [comment]
![alt](https://ae01.alicdn.com/kf/U4add15a5f6494791a6f06aacdc8984efe.jpg)

**Comment by BLumia** [comment]
我给的那个页面有说明啊，这个是有 C++ 组件的，没法直接装...

> 请注意，此组件依赖对应的 C++ QML 扩展，**故无法简单的提供 .plasmoid 包用以安装此组件，您需要手动构建此组件**，请参阅下方的简要构建说明或阅读详细的构建文档： https://github.com/BLumia/pineapple-calendar/wiki/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

**Comment by sonichy** [comment]
前员工就不是同名了，就是你。

**Comment by BLumia** [comment]
既然没有其它问题就关掉这个 issue 了，目前确实没有计划做适用于 DDE 的版本。印象里在我还在 Deepin 的时候就已经有人做过日历插件了，可以考虑去论坛搜一下。
