### ISSUE TITLE
打包了Fedora 版本，望更新wiki

### ISSUE THREAD

**Issue by liusen373** [BLumia/pineapple-calendar#4]
## 安装
```bash
sudo dnf copr enable liusen/hello
sudo dnf install pineapple-calendar
```
## 使用

安装之后手动添加部件即可

## 效果
共添加了2个部件，一个放在了任务栏，一个放在了桌面。

![img](https://user-images.githubusercontent.com/52489720/118385002-a636e900-b5fa-11eb-8343-e619c6b06326.png)

**Comment by BLumia** [comment]
哇感谢！

已经更新到了 Wiki 的安装指南页面中，并且开放了编辑，如果有不妥的地方或者需要补充的地方可以直接修改。

**Comment by oodzchen** [comment]
无法安装，是我哪里操作有问题吗？

> Do you really want to enable copr.fedorainfracloud.org/liusen/hello? [y/N]: y
错误：无法启用此项目。
项目 liusen/hello 不存在。

**Comment by BLumia** [comment]
这位维护者可能不再维护这个 fedora 包了？

你也可以尝试自己构建。不过作为额外说明，KDE 官方的日历组件现在也支持农历了（需要去设置里打开“替代日历”插件）

**Comment by oodzchen** [comment]
@BLumia 我才知道原来“备选日历”里面有农历，已经成功显示了，非常感谢
