### ISSUE TITLE
构建找不到ECM包

### ISSUE THREAD

**Issue by flickerhang** [BLumia/pineapple-calendar#6]
README 中能不能加上依赖列表啊，我这找不到这个包，也不知道到底是哪个库的。

**Comment by BLumia** [comment]
依赖列表不在 README，在 [安装指南 Wiki 页面](https://github.com/BLumia/pineapple-calendar/wiki/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97)

**Comment by BLumia** [comment]
很久没有得到你进一步的信息，暂时关闭这个 issue，请考虑按照上面提供的安装指南链接了解详细安装步骤和说明（也已于 a762d73 在 README 中追加了指向安装指南页面的链接）。若仍有问题，可继续回复 issue 并提供详细信息。
