### ISSUE TITLE
请求集成kde自带数字时钟的节假日（在小部件的设置面板中增加设置项）

### ISSUE THREAD

**Issue by devome** [BLumia/pineapple-calendar#8]
如题，请求集成kde自带数字时钟的节假日信息。

**Comment by BLumia** [comment]
不清楚你在使用什么版本，如果是 master 分支的版本的话，你只需要在 KDE 自带的数字时钟的设置中有开启节假日信息，然后换成我的这个版本，就会直接显示节假日信息的。

**Comment by devome** [comment]
我目前就是这样做的，感觉有点怪怪的。毕竟不是从本插件选项中选择的。

**Comment by BLumia** [comment]
> 我目前就是这样做的

所以你的问题已经解决了对吗？

> 毕竟不是从本插件选项中选择的。

因为之前没加任何设置，后来加设置只是为了配置任务栏上时间的显示格式。如果你有兴趣加这个设置的话欢迎 PR :)

**Comment by devome** [comment]
> 所以你的问题已经解决了对吗？（还是说这个 issue 的本意是加设置项？）

后者，希望增加设置顶。

> 因为之前没加任何设置，后来加设置只是为了配置任务栏上时间的显示格式。如果你有兴趣加这个设置的话欢迎 PR :)

目前还不具备kde开发这方面的技能，先去学习一下。

**Comment by BLumia** [comment]
马上 ubuntu 22.04 就要发了，最近也刚好有时间，就瞅了一眼。已经在目前的 master 分支增加了对应的支持（commit https://github.com/BLumia/pineapple-calendar/commit/306bac7d716ac22a5db1769ad7c07a57bb00e27b ），可以考虑更新试试看了（注：不支持且无计划 backport 到早期版本的 plasma 桌面环境中）。

如果遇到任何问题可以开个新 issue，如果有需要讨论的内容也可以在 discussion 里进行~
