### ISSUE TITLE
22.04打包版（见7楼）

### ISSUE THREAD

**Issue by mraandtux** [BLumia/pineapple-calendar#9]
**原标题：22.04编译后安装最新版扩展无法显示**

详细出错信息：

```
file:///usr/share/plasma/plasmoids/net.blumia.pineapple.calendar/contents/ui/main.qml:15:34: Type CalendarView unavailable

file:///usr/share/plasma/plasmoids/net.blumia.pineapple.calendar/contents/ui/CalendarView.qml:128:13: Type LocalCalendar.MonthView unavailable

file:///usr/share/plasma/plasmoids/net.blumia.pineapple.calendar/contents/ui/calendar/MonthView.qml:338:9: Type DaysCalendar unavailable

file:///usr/share/plasma/plasmoids/net.blumia.pineapple.calendar/contents/ui/calendar/DaysCalendar.qml:118:13: Type DayDelegate unavailable

file:///usr/share/plasma/plasmoids/net.blumia.pineapple.calendar/contents/ui/calendar/DayDelegate.qml:18:1: module "net.blumia.calendar" is not installed
```

**Comment by BLumia** [comment]
> 22.04

我看 ubuntu 官网暂时没说正式发布了 22.04 呀，是 beta 之类的版本吗？

> 安装最新版

最新版指的是目前的 master 分支版本（提交 https://github.com/BLumia/pineapple-calendar/commit/14e8105cac0f028202d19de85540f9d35d02af69 ）吗？

**Comment by mraandtux** [comment]
> 我看 ubuntu 官网暂时没说正式发布了 22.04 呀，是 beta 之类的版本吗？（还是说并不是指 ubuntu）
> 最新版指的是目前的 master 分支版本（提交 [14e8105](https://github.com/BLumia/pineapple-calendar/commit/14e8105cac0f028202d19de85540f9d35d02af69) ）吗？

今天刚换Ubuntu 22.04（写的时候还是测试版），21号才转正；最新版指的就是14e8105。

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/161790253-d89d0d05-5575-41fb-bb0f-ef02120917bd.png)

可是我并没有遇到你所说的问题呀，是在刚刚下载的 kubuntu 22.04 镜像（`kubuntu-22.04-beta-desktop-amd64.iso`，获取自[这里](https://cdimage.ubuntu.com/kubuntu/releases/22.04/beta/)）启动的 live 系统中测试的，也是上面提到的那个 commit。我本人用 Arch + KDE 在所可获取到的最新 plasma 桌面环境下也是可以用的。你确定你获取的是 master HEAD 的版本而不是我 release 中的版本吗？

**Comment by mraandtux** [comment]
> 也是上面提到的那个 commit。我本人用 Arch + KDE 在所可获取到的最新 plasma 桌面环境下也是可以用的。

已测试，自制提前deb打包版（编译至其他位置，再合并打包）无法显示，但按照指南编译的则可以显示。不知道为什么提前deb打包版会出现module "net.blumia.calendar" is not installed错误。

**Comment by BLumia** [comment]
提供下打出来的包和打包过程的步骤？只凭目前的描述没法判断原因= =

net.blumia.calendar 是一个 QML C++ 模块，需要留意下这个。

**Comment by mraandtux** [comment]
出错原因：
由于 /lib/ 文件夹摆放位置有误（ /usr/lib/ 不是0.1.1打包版摆放位置），农历就此无法显示，#2 提及的用户目录安装方式也不行。

正确的打包方式是：
* 依照指南编译，安装位置填plasma-addons-pineapple-calendar_x.x.x-x
* /lib/ 文件夹完整路径： /lib/x86_64-linux-gnu/qt5/qml/net/blumia/calendar/ （若）
* /share/ 的内容不变，并移至 /usr/
* [照Ubuntu官方论坛的帖子轻松制作deb包](https://ubuntuforums.org/showthread.php?t=910717)

[真·22.04打包版：plasma-addons-pineapple-calendar_0.1.2-1.zip](https://github.com/BLumia/pineapple-calendar/files/8438978/plasma-addons-pineapple-calendar_0.1.2-1.zip)

**Comment by BLumia** [comment]
感谢跟进，在 ubuntu 正式发布 22.04 LTS 后我会打个 0.2.0 的 tag。因为跟随了 plasma 更新了日历组件，改动稍微大一些，印象里甚至没法直接在 debian bullseye 里用目前的 master HEAD 版，所以不是 0.1.2。

**Comment by BLumia** [comment]
今天留意了一下发现 https://github.com/BLumia/pineapple-calendar/commit/14e8105cac0f028202d19de85540f9d35d02af69 版本的小部件右键菜单里的两个调 KCM 的设置项在 Arch 环境下失效了，就做了下更新 https://github.com/BLumia/pineapple-calendar/commit/bf1add496d446a69b0467a5209404db21950188e 。暂时还没测在 ubuntu 22.04 下的效果，我打算等 ubuntu 22.04 正式发布后再测，如果你有兴趣的话也可以试试看，目前 master 分支也包含了一些别的改动 :)

**Comment by BLumia** [comment]
![](https://user-images.githubusercontent.com/10095765/164233270-65d87635-a119-4ca6-8e71-919c3285aad5.png)

已在 ubuntu 22.04 LTS 的 RC 版本中测试没问题，[0.2.0](https://github.com/BLumia/pineapple-calendar/releases/tag/0.2.0) tag 已发。就先关掉 issue 啦~
